//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_DSW1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int idCliente { get; set; }
        public Nullable<int> idDistrito { get; set; }
        [Required(ErrorMessage = "Ingrese DNI")]
        public string dni_clie { get; set; }
        [Required(ErrorMessage = "Ingrese nombre")]
        public string nom_cli { get; set; }
        [Required(ErrorMessage = "Ingrese apellido")]
        public string ape_cli { get; set; }
        [Required(ErrorMessage = "Ingrese correo electronico")]
        public string mail_cli { get; set; }
        [Required(ErrorMessage = "Ingrese telefono")]
        public string tel_cli { get; set; }
    
        public virtual Distrito Distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
